重构Popup页面的ui
scriptscat/scriptcat pull request #6
Opened 2021-09-03 01:29 UTC by Przeblysk

- 新增@qvant/qui UI 库依赖
- 重构Popup页面样式布局

2021-09-03 01:52 UTC, CodFrm requested changes
有冲突，rebase一下最新的develop/ui解决一下冲突，那块好像是可以直接删除的

2021-09-03 01:52 UTC, CodFrm commented on src/views/pages/Popup/indexOld.vue
> +<template>
可以不留old文件

2021-09-03 01:52 UTC, CodFrm commented on src/views/pages/Popup/index.vue
> +        <a class="entry" href="https://bbs.tampermonkey.net.cn/forum-2-1.html" target="_blank">获取脚本</a>
如果修改的话，这里可以顺路改成  https://scriptcat.org/ 呗

2021-09-03 01:57 UTC, CodFrm commented on public/popup.html
>              rel="stylesheet"
这个是vuetify框架用的icon，如果没用了的话，可以删除？

2021-09-03 02:06 UTC, Przeblysk commented on public/popup.html
>              rel="stylesheet"
可以我等会删了

2021-09-03 02:27 UTC, CodFrm approved these changes

2021-09-03 02:35 UTC, CodFrm commented
我这里`npm run build`报错
```
scriptcat\node_modules\webpack\lib\util\deterministicGrouping.js:346
                                        addSizeTo(rightSize, group.nodes[right].size);
                                                                                ^

TypeError: Cannot read property 'size' of undefined
```

大佬那边能build成功吗？猜测是`webpack.prod.babel.ts`配置了`splitChunks`的原因，我再看看

2021-09-03 02:36 UTC, Przeblysk commented
> 我这里`npm run build`报错
> 
> ```
> scriptcat\node_modules\webpack\lib\util\deterministicGrouping.js:346
>                                         addSizeTo(rightSize, group.nodes[right].size);
>                                                                                 ^
> 
> TypeError: Cannot read property 'size' of undefined
> ```
> 
> 大佬那边能build成功吗？猜测是`webpack.prod.babel.ts`配置了`splitChunks`的原因，我再看

2021-09-03 02:37 UTC, Przeblysk commented
淦点错了。我看看我这build有没有问题

2021-09-03 02:43 UTC, Przeblysk commented
> 我这里`npm run build`报错
> 
> ```
> scriptcat\node_modules\webpack\lib\util\deterministicGrouping.js:346
>                                         addSizeTo(rightSize, group.nodes[right].size);
>                                                                                 ^
> 
> TypeError: Cannot read property 'size' of undefined
> ```
> 
> 大佬那边能build成功吗？猜测是`webpack.prod.babel.ts`配置了`splitChunks`的原因，我再看看


> 我这里`npm run build`报错
> 
> ```
> scriptcat\node_modules\webpack\lib\util\deterministicGrouping.js:346
>                                         addSizeTo(rightSize, group.nodes[right].size);
>                                                                                 ^
> 
> TypeError: Cannot read property 'size' of undefined
> ```
> 
> 大佬那边能build成功吗？猜测是`webpack.prod.babel.ts`配置了`splitChunks`的原因，我再看看

可能是的，如果是包大小的问题，我看下ui库改成按需引入吧

2021-09-03 02:44 UTC, CodFrm commented
```ts
import merge from "webpack-merge";
import commonConfig from "./webpack.config.babel";
import TerserPlugin from "terser-webpack-plugin";
import { Configuration } from "webpack";

// 减小扩展包大小
const localConfig: Configuration = {
    devtool: false,
    optimization: {
        minimize: true,
        minimizer: [new TerserPlugin()],
        splitChunks: {
            chunks: "all",
            minSize: 307200,
            maxSize: 4194304,
            cacheGroups: {
                monaco: {
                    test: /[\\/]node_modules[\\/]monaco-editor/,
                    minSize: 307200,
                    maxSize: 4194304,
                    name: "monaco",
                    chunks: "all",
                    priority: 1,
                    reuseExistingChunk: true,
                }
            },
        },
    },
};

export default merge(commonConfig, localConfig);

```

我现在将配置修改成这样是可以的，我验证下有没有问题

2021-09-03 02:46 UTC, CodFrm commented
> ```ts
> 4194304
> ```

主要是解决单个文件太大 firefox那边只支持最高4M的问题，另外也优化扩展文件的大小，不然可以到10多M

2021-09-03 02:55 UTC, CodFrm commented
好像还有几个问题，麻烦大佬看一下了

1.脚本有注册菜单的选项
![image](https://user-images.githubusercontent.com/22783163/131943321-66109609-4c40-40ae-a24d-21a2671eb616.png)

测试脚本：
https://bbs.tampermonkey.net.cn/thread-916-1-1.html

2.后台脚本有运行中和停止的状态
![image](https://user-images.githubusercontent.com/22783163/131943585-842be0b1-9ad1-4181-99d7-382c570818d5.png)

测试脚本：https://bbs.tampermonkey.net.cn/thread-417-1-1.html

3.窗口大小变换的时候好像有问题（好像是扩展的，这个我也不清楚怎么解决，之前一直有）

两个脚本-》一个脚本
![image](https://user-images.githubusercontent.com/22783163/131943647-d4fe8434-893b-48ca-9442-9565b0e13d65.png)

![image](https://user-images.githubusercontent.com/22783163/131943674-d1a29fca-00cf-4e9c-b482-c953faa34bdc.png)

2021-09-03 02:58 UTC, Przeblysk commented
> 好像还有几个问题，麻烦大佬看一下了
> 
> 1.脚本有注册菜单的选项
> ![image](https://user-images.githubusercontent.com/22783163/131943321-66109609-4c40-40ae-a24d-21a2671eb616.png)
> 
> 测试脚本：
> https://bbs.tampermonkey.net.cn/thread-916-1-1.html
> 
> 2.后台脚本有运行中和停止的状态
> ![image](https://user-images.githubusercontent.com/22783163/131943585-842be0b1-9ad1-4181-99d7-382c570818d5.png)
> 
> 测试脚本：https://bbs.tampermonkey.net.cn/thread-417-1-1.html
> 
> 3.窗口大小变换的时候好像有问题（好像是扩展的，这个我也不清楚怎么解决，之前一直有）
> 
> 两个脚本-》一个脚本
> ![image](https://user-images.githubusercontent.com/22783163/131943647-d4fe8434-893b-48ca-9442-9565b0e13d65.png)
> 
> ![image](https://user-images.githubusercontent.com/22783163/131943674-d1a29fca-00cf-4e9c-b482-c953faa34bdc.png)

好的，收到

2021-09-03 02:59 UTC, CodFrm commented
十分感谢 
![C188EE3CFE10EAE7F3CDF254C5B04840](https://user-images.githubusercontent.com/22783163/131944036-d499ce95-f516-4960-82af-a28c8f45def1.png)

2021-09-03 07:04 UTC, CodFrm commented
对了 还有这个 公告 点击会弹出通知那一块 
![2T46NJ_$69ZLQ%ZGEOH525Q](https://user-images.githubusercontent.com/22783163/131964468-f71977b9-ef28-4d87-857c-71aaa49c7b8d.png)


![image](https://user-images.githubusercontent.com/22783163/131964441-19dd760d-b0c9-452f-a951-d0f23256f5bb.png)

2021-09-04 15:19 UTC, Przeblysk commented
[build的报错的问题应该这个](https://github.com/webpack/webpack/issues/12487)
调整小了cacheGroups 下 vendor 的 minSize后就可以了

2021-09-04 15:19 UTC, Przeblysk commented
[build的报错的问题应该这个](https://github.com/webpack/webpack/issues/12487)
调整小了cacheGroups 下 vendor 的 minSize后就可以了

2021-09-05 04:02 UTC, CodFrm commented on package-lock.json
> -    "packages": {
lockfileVersion 变成1了，更新npm到 7以上的版本解决

2021-09-06 06:24 UTC, merged